#!/bin/bash

#$ -M rnahm@nd.edu   # Email address for job notification
#$ -m abe            # Send mail when job begins, ends and aborts
#$ -pe smp 14         # Specify parallel environment and legal core size
#$ -q long           # Specify queue
#$ -N local-stockfish2      # Specify job name


module use -a ~/privatemodules
module load golang/1.20      # Required modules

 # Application to execute
cd ~/distsys-chess-engine
./bin/local 200


